name: CI/CD with Terraform
on:
  push:
    branches:
      - Complete-CI-CD-with-Terraform-AWS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
  TF_STATE_S3_BUCKET: ${{ secrets.AWS_STATE_BUCKET_NAME }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_S3_BUCKET }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ env.AWS_DEFAULT_REGION }}"
        working-directory: ./terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -var="region=${{ env.AWS_DEFAULT_REGION }}" -var="public_key=${{ env.PUBLIC_SSH_KEY }}" -var="private_key=${{ env.PRIVATE_SSH_KEY }}" -out=tfplan -input=false
        working-directory: ./terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false tfplan
        working-directory: ./terraform
